/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    baseURL: 'http://dnoram8.cloudfoundry.com/',
    models: [
        'Task',
        'Duser',
        'LocalUser'
    ],
    stores: [
        'TasksStore',
        'ResultStore',
        'AddressTypeStore'
    ],
    views: [
        'MyNavigationView',
        'ManageTaskList',
        'AddTaskForm',
        'TaskResultList',
        'MapPanel',
        'MyContainer1',
        'MyContainer',
        'MainApplicationView'
    ],
    controllers: [
        'MainController'
    ],
    icon: {
        '57': 'images/dNORAM5.png',
        '72': 'images/dNORAM5.png',
        '114': 'images/dNORAM5.png',
        '144': 'images/dNORAM5.png'
    },
    name: 'MyApp',
    isIconPrecomposed: false,

    launch: function() {

        Ext.create('MyApp.view.MainApplicationView', {fullscreen: true});
    }

});
