/*
 * File: app/view/ManageTaskList.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ManageTaskList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.manageTaskListAlias',

    config: {
        id: 'manageTaskList',
        emptyText: 'Please create task',
        loadingText: 'Retrieving your tasks ...',
        store: 'tasksStore',
        onItemDisclosure: true,
        itemTpl: [
            '<tpl if="isCompleted == false"> <div>{title}</div><tpl else><div style="text-decoration: line-through">{title}</div></tpl><div style="font-size:70%">Duration: {duration} min.</div><span class="deleteplaceholder"></span>'
        ]
    }

});