// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.susanku.dnoram8.domain;

import com.susanku.dnoram8.domain.Duser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Duser_Roo_Configurable {
    
    declare @type: Duser: @Configurable;
    
}
