/*
 * File: app/store/ResultStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.ResultStore', {
    extend: 'Ext.data.Store',
    alias: 'store.resultStore',
    requires: [
        'MyApp.model.Task'
    ],

    config: {
        model: 'MyApp.model.Task',
        storeId: 'resultStore',
        proxy: {
            type: 'ajax',
            enablePagingParams: false,
            url: 'http://dnoram8.cloudfoundry.com/getbesttask',
            reader: {
                type: 'json',
                rootProperty: 'tasks'
            }
        },
        grouper: {
            groupFn: function(record) {
                var mainController = MyApp.app.getController('MainController');
                console.log('main controller : ' + mainController);
                var picker = mainController.getAvailableTimePicker();

                var min = parseInt(picker.getValue()['MinPickerSlot']);
                var hours = parseInt(picker.getValue()['HoursPickerSlot']);
                var availableTime = hours*60+min;

                if(record.get('totalTaskTime') <= availableTime) {
                    return "Best Tasks around this location";
                } else {
                    return "Your other tasks";
                }

            }
        }
    }
});