/*
 * File: app/view/AddTaskForm.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AddTaskForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.addTaskFormAlias',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Spinner',
        'Ext.Label',
        'Ext.field.Select',
        'Ext.field.TextArea',
        'Ext.field.Toggle',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.field.Text',
        'Ext.MessageBox',
        'Ext.data.Store'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        name: 'title',
                        placeHolder: 'Task Title*'
                    },
                    {
                        xtype: 'spinnerfield',
                        label: 'Duration',
                        labelWidth: '37%',
                        name: 'duration',
                        required: true,
                        minValue: 0,
                        increment: 5
                    },
                    {
                        xtype: 'label',
                        html: 'in minutes',
                        style: 'padding-left:40%;font-size:12px;color:#aaa;'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                name: 'addressFieldFieldSet',
                items: [
                    {
                        xtype: 'selectfield',
                        label: 'Address',
                        labelWidth: '37%',
                        name: 'addressType',
                        required: true,
                        value: 'Current',
                        store: 'addressTypeStore'
                    },
                    {
                        xtype: 'textareafield',
                        height: 80,
                        hidden: true,
                        labelWidth: 0,
                        name: 'formattedAddress',
                        placeHolder: 'Type address or street intersection... ',
                        maxRows: 1
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textareafield',
                        label: '',
                        labelWidth: 0,
                        name: 'notes',
                        placeHolder: 'Notes..'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'togglefield',
                        label: 'Completed',
                        labelWidth: '37%',
                        name: 'isCompleted'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        name: 'delete',
                        docked: 'right',
                        hidden: true,
                        ui: 'plain',
                        iconCls: 'trash',
                        iconMask: true
                    },
                    {
                        xtype: 'button',
                        name: 'mapIt',
                        disabled: false,
                        docked: 'left',
                        hidden: true,
                        ui: 'plain',
                        iconCls: 'locate',
                        iconMask: true
                    }
                ]
            }
        ]
    }

});