/*
 * File: app/view/MainApplicationView.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainApplicationView', {
    extend: 'Ext.Container',
    alias: 'widget.mainApplicationView',

    requires: [
        'MyApp.view.MyNavigationView',
        'Ext.Panel',
        'Ext.Img',
        'Ext.navigation.View',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Label',
        'Ext.util.DelayedTask'
    ],

    config: {
        layout: 'card',
        scrollable: false,
        items: [
            {
                xtype: 'panel',
                name: 'welcome',
                ui: '',
                scrollable: false,
                layout: {
                    type: 'vbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'image',
                        height: 480,
                        ui: '',
                        width: 320,
                        src: 'resources/images/dNORAM.png'
                    }
                ]
            },
            {
                xtype: 'mynavigationview',
                name: 'appcontainer'
            },
            {
                xtype: 'panel',
                name: 'info',
                layout: {
                    type: 'vbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'button',
                                handler: function(button, event) {

                                    button.up("mainApplicationView").animateActiveItem(1,{type:'flip',duration:800});
                                },
                                ui: 'plain',
                                iconCls: 'home',
                                iconMask: true
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: '<div id="infoDiv"><p><span style="font-weight:bold;font-style:italic">Softrism Inc</span> was born in 2012 with an intent to contribute to the mobile app world by bringing in most apt and easy to use applications to our customers. </p> <p>Our focus is to improve user productivity in the most intutive way possible.</p></div>',
                        style: 'font-size:14px;'
                    },
                    {
                        xtype: 'label',
                        docked: 'bottom',
                        html: '&copy; 2012 SUSANKU Inc.',
                        style: 'font-size:10px;text-align:center; padding:5px;'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onContainerShow',
                event: 'show'
            }
        ]
    },

    onContainerShow: function(component, eOpts) {


        //create the delayed task instance with our callback
        var task = Ext.create('Ext.util.DelayedTask', function() {
            console.log('callback!');
            component.animateActiveItem(1,{duration:2000,type: 'slide', direction: 'left'});
            task.cancel();
        });

        task.delay(1000);
    }

});