/*
 * File: app/view/ManageTaskList.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ManageTaskList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.manageTaskListAlias',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        id: 'manageTaskList',
        emptyText: 'Please create task',
        loadingText: 'Retrieving your tasks ...',
        store: 'tasksStore',
        onItemDisclosure: true,
        itemTpl: [
            '<tpl if="isCompleted == false"> ',
            '    <div style="font-weight:bold;">{title:ellipsis(21, true)}</div>',
            ' <tpl else>',
            '     <div style="font-weight:bold;text-decoration: line-through">{title:ellipsis(21, true)}</div>',
            ' </tpl>',
            ' <div style="font-size:80%;font-style:italic;">Duration: {duration} min</div>',
            '    <span class="deleteplaceholder"></span>',
            ''
        ]
    }

});