/*
 * File: app/view/MyImage.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyImage', {
    extend: 'Ext.Img',
    alias: 'widget.myimage',

    config: {
        height: 201,
        id: 'manageTasksButtonImage',
        width: 201,
        src: 'resources/images/manageTasksButton.jpg'
    }

});